### ISSUE TITLE
Version 1.4.0 broken

### ISSUE THREAD

**Issue by fubhy** [fridays/next-routes#156]
I am getting this error after upgrading to 1.4.0. Will investigate later once I find time and submit a patch: 

```
TypeError: _pathToRegexp2.default.compile is not a function
```

**Comment by fubhy** [comment]
Manually adding path-to-regexp to my dependencies solves it for now.

**Comment by fridays** [comment]
I can’t reproduce, the dependency didn’t change. Feel free to reopen if you think the problem is with this lib
