### ISSUE TITLE
next-routes is not working in iOS 8.4

### ISSUE THREAD

**Issue by nndung179** [fridays/next-routes#32]
Hi!

Currently, I met some issues on iOS 8.4 devices. 

When using `<Link>`
```
printWarning — commons.js:102Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.

React DOM tree root should always have a node reference.
```

When using `Router.pushRoute('index', params)`

```
TypeError: undefined is not a function (evaluating '_this5.keyNames.includes(key)')
```

**Comment by nndung179** [comment]
I just added `babel-polyfill` & everything work fine. Could I update a document to mention about this issue?

**Comment by fridays** [comment]
Seems related to https://github.com/fridays/next-routes/issues/27 and https://github.com/zeit/next.js/pull/1808

**Comment by nndung179** [comment]
I have create 2 PR. You could check it out: 

+ update document
https://github.com/fridays/next-routes/pull/34

+ replace function includes with indexOf
https://github.com/fridays/next-routes/pull/33

**Comment by fridays** [comment]
Thank you! It should be fixed with related problems by https://github.com/fridays/next-routes/pull/37. Please update to 1.0.25 and check again

**Comment by HaNdTriX** [comment]
Is this still an issue @nndung179?
